# Generated by Django 3.1 on 2020-08-10 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldinfo',
            name='createTime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='foldinfo',
            name='createdBy',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floderCreatedByCreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='创建人ID'),
        ),
        migrations.AddField(
            model_name='foldinfo',
            name='deletedTime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='foldinfo',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='是否正常'),
        ),
        migrations.AddField(
            model_name='foldinfo',
            name='updateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='foldinfo',
            name='updatedBy',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floderUpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='修改人ID'),
        ),
    ]
