# Generated by Django 3.1 on 2020-08-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanage', '0002_auto_20200810_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoldInfo',
        ),
    ]
