# Generated by Django 3.1 on 2020-08-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanage', '0005_auto_20200810_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='extension',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='扩展名'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='文件大小'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='file_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文件类型'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文件原始名称'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文件路径'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='sha1',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='sha1'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文件名称'),
        ),
    ]
