# Generated by Django 3.1 on 2020-08-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanage', '0006_auto_20200811_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='file',
            field=models.FileField(default='', upload_to='upload'),
        ),
    ]
