# Generated by Django 3.1 on 2020-08-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanage', '0008_auto_20200811_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='file_size',
        ),
    ]
