# Generated by Django 3.1 on 2020-08-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200819_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryinfo',
            options={'verbose_name': '栏目管理', 'verbose_name_plural': '栏目管理'},
        ),
    ]
