# Generated by Django 3.1 on 2020-08-19 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0003_auto_20200819_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='修改时间')),
                ('deletedTime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='删除时间')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否正常')),
                ('content_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='文章标题')),
                ('content_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='文章跳转链接地址')),
                ('content_details', models.TextField(blank=True, null=True, verbose_name='文章内容')),
                ('content_keyword', models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字')),
                ('content_description', models.CharField(blank=True, max_length=400, null=True, verbose_name='文章描述')),
                ('content_img', models.CharField(blank=True, max_length=255, null=True, verbose_name='文章缩略图')),
                ('content_sort', models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义顺序')),
                ('content_display', models.BooleanField(default=True, max_length=255, verbose_name='是否显示')),
                ('content_type', models.BooleanField(blank=True, max_length=255, null=True, verbose_name='文章类型')),
                ('content_pub_datetime', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='发布时间')),
                ('content_hit', models.IntegerField(blank=True, max_length=22, null=True, verbose_name='点击次数')),
                ('content_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.categoryinfo', verbose_name='所属栏目')),
                ('createdBy', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人ID')),
                ('updatedBy', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='修改人ID')),
            ],
            options={
                'verbose_name': '内容管理',
                'verbose_name_plural': '内容管理',
            },
        ),
    ]
