# Generated by Django 3.1 on 2020-08-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_hit',
            field=models.IntegerField(blank=True, null=True, verbose_name='点击次数'),
        ),
    ]
