# Generated by Django 3.1 on 2020-08-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20200819_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='自定义顺序'),
        ),
    ]
