# Generated by Django 2.1.7 on 2020-07-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinfo',
            name='device_type',
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='设备类型'),
        ),
        migrations.DeleteModel(
            name='DeviceType',
        ),
    ]
