# Generated by Django 2.1.7 on 2020-07-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmms', '0003_auto_20200727_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='hostname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IP/域名'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='经度'),
        ),
    ]
